name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      ftoken: ${{ secrets.ftoken }}
    
    steps:
    - name: Build the Docker image
      run: |
           docker pull fluidattacks/forces:new
           docker run fluidattacks/forces:new forces --token ${{env.ftoken}} -vv --strict --breaking 9.0
